### ISSUE TITLE
[BE] CI/CD 설정

### ISSUE THREAD

**Issue by jinlee1703** [endless-horses/oot-was#12]
## Task

- [x]  배포 먼저 해보기(Docker or Git or etc.)
- [x] CI/CD 공부하기
- [x] Github Actions 공부하기
- [x] CI/CD 파이프라인 구축
