### ISSUE TITLE
[BE] API 주소 수정

### ISSUE THREAD

**Issue by SubiHwang** [endless-horses/oot-was#35]
## Description

- 기존의 API 주소인 /*patterns* 를 /api/*patterns* 로 변경한다.

## Task

- [ ] WheelController 에서 수정
- [ ] AccessoryController 에서 수정
- [ ] PatternController 에서 수정
- [ ] ColorController 에서 수정
- [ ] FontController 에서 수정
