### ISSUE TITLE
[BE] CORS 에러 해결

### ISSUE THREAD

**Issue by jinlee1703** [endless-horses/oot-was#48]
## Description

배포한 웹 어플리케이션에서 CORS 오류 발생

<img width="998" alt="image" src="https://github.com/endless-horses/oot-was/assets/68031450/f7f92a35-6cc8-4ac4-ace1-1bac0d5e0266">

## Solution

- application.yml의 `cors.allowed-origins`에 배포한 origin 주소 추가하기 (노션 참고)
  
  <img width="312" alt="image" src="https://github.com/endless-horses/oot-was/assets/68031450/2b2d65ad-455f-487f-851b-ca3ecc6278c2">

## Task

- [x] application.yml 최신화 하기
- [x] application.yml의 `cors.allowed-origins`에 배포한 origin 주소 추가하기
- [x] Actions Secret 최신화하기

**Comment by SubiHwang** [comment]
확인했습니다!
